apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: ramigs/conversao-temperatura:v1
          ports:
           - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: express 
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30000
  type: NodePort